// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubPin } from "./SubPin";
import type { TruthTable } from "./TruthTable";

export type Behavior = { name: string, logic: TruthTable, inputs: Array<SubPin>, outputs: Array<SubPin>, };
