// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventBit } from "./EventBit";
import type { TruthTable } from "./TruthTable";

export type Behavior = { name: string, logic: TruthTable, inputs: Array<EventBit>, outputs: Array<EventBit>, };
