// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Event = "CellClear" | "Cell" | "CellNext" | "Time" | "Pulse" | "Memory" | "Random" | "Chance" | "Obstacle" | "Kill" | "Direction" | "Halted" | "SpawnAnt" | "Die";
