// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MidiConfig = { 
/**
 * set channel to 1-16 or set to 0 to ignore
 */
out_ch: number, offset: number, };
