// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Pin = "Clear" | "Cell" | "Next" | "Time" | "Pulse" | "Mem" | "Random" | "Chance" | "Collide" | "Kill" | "Dir" | "Halt" | "AntDir" | "AntMem" | "AntSpawn" | "Signal" | "ExtIn" | "ExtOut" | "Die";
