// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Pin = "AntId" | "ChildRotation" | "ChildLeft" | "ChildMem" | "ChildLayer" | "Rotation" | "RotateLeft" | "RotateZero" | "TieBreaker" | "Halt" | "Wait" | "Die" | "Kill" | "Tile" | "EmptyTile" | "NearbyTile" | "NearbyAnt" | "NearbyId" | "NearbyMem" | "BirthTick" | "Mem" | "Counter" | "Clock" | "Noise" | "Probability" | "Signal" | "ExtIn" | "ExtOut";
