// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Pin = "SpawnId" | "SpawnRotation" | "SpawnMem" | "SpawnLayer" | "Rotation" | "Fast" | "Halt" | "Wait" | "Die" | "Kill" | "Tile" | "EmptyTile" | "NearbyTile" | "NearbyAnt" | "NearbyId" | "NearbyMem" | "BirthTick" | "Counter" | "Mem" | "Noise" | "Signal" | "ExtIn" | "ExtOut";
