// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IoType } from "./IoType";
import type { Pin } from "./Pin";

export type PinDefinition = { pin: Pin, code: string, size: number, io_type: IoType | null, };
