// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RenderMask = "none" | "tile" | "layers" | "dir" | "id" | "birth_tick" | "input_bits" | "mem";
