// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TruthTable = { input_count: number, output_count: number, entries: Array<number>, };
