// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BorderMode } from "./BorderMode";
import type { ColorMode } from "./ColorMode";
import type { StartingPos } from "./StartingPos";

export type WorldConfig = { 
/**
 * width in pixels
 */
width: number, 
/**
 * height in pixels
 */
height: number, 
/**
 * rendered frames per second
 */
fps: number | null, 
/**
 * simulated ticks per frame (defaults to 1)
 */
speed: number | null, 
/**
 * simulation tick limit
 */
ticks: number | null, 
/**
 * amount of ticks after which a cell will automatically reset
 */
decay: number | null, 
/**
 * amount of ms to sleep for after end of simulation, i.e. between loops
 */
sleep: number | null, 
/**
 * re-run simulation after it ends
 */
looping: boolean, 
/**
 * behavior if ants touch the worlds border
 */
border_mode: BorderMode, 
/**
 * position of the first ant
 */
starting_pos: StartingPos, 
/**
 * max number of ants before additional spawning gets blocked
 */
ant_limit: number | null, color_mode: ColorMode, noise_seed: number | null, hide_title: boolean, description: string, };
