// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BorderMode } from "./BorderMode";
import type { ColorMode } from "./ColorMode";
import type { StartingPos } from "./StartingPos";

export type WorldConfig = { 
/**
 * width in pixels
 */
width: number, 
/**
 * height in pixels
 */
height: number, 
/**
 * simulated ticks per frame (defaults to 1)
 */
speed: number | null, 
/**
 * simulation tick limit
 */
ticks: number | null, 
/**
 * amount of ticks after which a cell will automatically reset
 */
decay: number | null, 
/**
 * re-run simulation after it ends
 */
looping: boolean, 
/**
 * behavior if ants touch the worlds border
 */
border_mode: BorderMode, 
/**
 * position of the first ant
 */
start_pos: StartingPos, 
/**
 * first tick to render
 */
start_tick: number, 
/**
 * direction value (0-7) for start ant
 */
start_dir: number, 
/**
 * max number of ants before additional spawning gets blocked
 */
ant_limit: number | null, noise_seed: number | null, description: string, 
/**
 * rendered frames per second
 */
fps: number | null, 
/**
 * don't render ants
 */
hide_ants: boolean, 
/**
 * amount of ms to sleep for after end of simulation, i.e. between loops
 */
sleep: number | null, 
/**
 * 16 ASCII characters to render cells, start is value = 0
 * can also set to empty string to get a default ASCII palette
 */
ascii: string | null, 
/**
 * changes how colors are rendered
 */
color_mode: ColorMode, 
/**
 * 1 to 8 characters as key bindings, representing K0-K7 in ascending order
 */
keys: string | null, };
