// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Behavior } from "./Behavior";
import type { WorldConfig } from "./WorldConfig";

export type WorldProperties = { name: string | null, ants: { [key in number]: Behavior }, cfg: WorldConfig, };
